
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
server:
  port: 8085
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-c/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign

  
