
server:
  port: 8082

spring:
  data:
    solr:
      host: http://127.0.0.1:8099/solr
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:8066/TESTDB?ServerTimezone=HongKong&useUnicode=true&characterEncoding=utf-8
    username: root
  application:
    name: service-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


mybatis:
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jk.model

