
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  data: 
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: service-feign
  

