
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 20000
    database: 0
    
      
    cluster:
      nodes: 192.168.70.129:6379,192.168.70.129:6380,192.168.70.129:6381
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: service-feign
  

